name: Test grok patterns
on: [push, workflow_dispatch]
jobs:
  test-patterns:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: gem install jls-grok minitest
      - run: ruby test/test.rb
